/*
 * ==============================================================================
 * ⚠️ WARNING: THIS FILE IS DEPRECATED ⚠️
 * ==============================================================================
 *
 * This file (dnd-app.js) is no longer the active source code for the DnD app.
 *
 * The JavaScript for the DnD 2014 application has been refactored and split
 * into multiple modular parts for easier maintainability.
 *
 * The active code is now located in:
 *    Game/DnD-2014/js/dnd-app-part-*.js
 *
 * At runtime, `index.php` loads `dnd-app.php`, which dynamically concatenates
 * all the `js/dnd-app-part-*.js` files together.
 *
 * DO NOT EDIT THIS FILE. Your changes will be ignored.
 * If you need to make changes to the frontend logic, please edit the files
 * inside the `Game/DnD-2014/js/` directory.
 *
 */
console.warn("dnd-app.js is deprecated. Please check Game/DnD-2014/js/dnd-app-part-*.js instead.");
